name: poc-yaml-xiuno-bbs-cvnd-2019-01348-reinstallation
binding: 86e14d91-7868-4189-bc5b-f5d0ad35f9ef
manual: true
detail:
    author: 清风明月(www.secbook.info)
    links:
        - https://www.cnvd.org.cn/flaw/show/CNVD-2019-01348
    vulnerability:
        id: CT-158393
        level: high
    influence_version: =< Xiuno BBS 4.0.4
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /install/
            headers:
                Accept-Encoding: deflate
            follow_redirects: false
        expression: response.status == 200 && response.body.bcontains(b"/view/js/xiuno.js") && response.body_string.contains("Choose Language (选择语言)")
expression: r0()
