name: yaml-poc-smartbear-swagger_ui-unauthorized_access-CT-515802
binding: ac9768bd-d6d9-49ec-badf-00a4de16c3e5
detail:
    author: lianjian.chen
    links:
        - http://cn-sec.com/archives/937812.html
    vulnerability:
        id: 846c630d-eabd-4d66-b138-6ccd71a727bb
        level: high
    warning: Harmless
transport: http
payloads:
    payloads:
        default:
            checker: |-
                '("swagger": ?"2\\.0"|"openapi": ?"3\\.0\\.\\d"|"swaggerVersion":)'
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /swagger/v1/swagger.json
        expression: response.status == 200 && response.headers["Content-Type"].contains("application/json") && checker.bmatches(response.body)
    r1:
        request:
            cache: true
            method: GET
            path: /api/swagger-resources
        expression: response.status == 200 && response.headers["Content-Type"].contains("application/json") && checker.bmatches(response.body)
    r2:
        request:
            cache: true
            method: GET
            path: /api/api-docs
        expression: response.status == 200 && response.headers["Content-Type"].contains("application/json") && checker.bmatches(response.body)
    r3:
        request:
            cache: true
            method: GET
            path: /api/apidocs
        expression: response.status == 200 && response.headers["Content-Type"].contains("application/json") && checker.bmatches(response.body)
    r4:
        request:
            cache: true
            method: GET
            path: /api/swagger-ui.json
        expression: response.status == 200 && response.headers["Content-Type"].contains("application/json") && checker.bmatches(response.body)
    r5:
        request:
            cache: true
            method: GET
            path: /api/swagger.json
        expression: response.status == 200 && response.headers["Content-Type"].contains("application/json") && checker.bmatches(response.body)
    r6:
        request:
            cache: true
            method: GET
            path: /api/v1/api-docs
        expression: response.status == 200 && response.headers["Content-Type"].contains("application/json") && checker.bmatches(response.body)
    r7:
        request:
            cache: true
            method: GET
            path: /api/v1/swagger-ui.json
        expression: response.status == 200 && response.headers["Content-Type"].contains("application/json") && checker.bmatches(response.body)
    r8:
        request:
            cache: true
            method: GET
            path: /api/v1/swagger.json
        expression: response.status == 200 && response.headers["Content-Type"].contains("application/json") && checker.bmatches(response.body)
    r9:
        request:
            cache: true
            method: GET
            path: /api/v1/swagger/
        expression: response.status == 200 && response.headers["Content-Type"].contains("application/json") && checker.bmatches(response.body)
    r10:
        request:
            cache: true
            method: GET
            path: /api/v2/swagger-ui.json
        expression: response.status == 200 && response.headers["Content-Type"].contains("application/json") && checker.bmatches(response.body)
    r11:
        request:
            cache: true
            method: GET
            path: /api/v2/swagger.json
        expression: response.status == 200 && response.headers["Content-Type"].contains("application/json") && checker.bmatches(response.body)
    r12:
        request:
            cache: true
            method: GET
            path: /swagger-resources
        expression: response.status == 200 && response.headers["Content-Type"].contains("application/json") && checker.bmatches(response.body)
    r13:
        request:
            cache: true
            method: GET
            path: /swagger-resources/configuration/security
        expression: response.status == 200 && response.headers["Content-Type"].contains("application/json") && checker.bmatches(response.body)
    r14:
        request:
            cache: true
            method: GET
            path: /swagger-resources/configuration/ui
        expression: response.status == 200 && response.headers["Content-Type"].contains("application/json") && checker.bmatches(response.body)
    r15:
        request:
            cache: true
            method: GET
            path: /swagger/Default/swagger.json
        expression: response.status == 200 && response.headers["Content-Type"].contains("application/json") && checker.bmatches(response.body)
    r16:
        request:
            cache: true
            method: GET
            path: /swagger-ui.json
        expression: response.status == 200 && response.headers["Content-Type"].contains("application/json") && checker.bmatches(response.body)
    r17:
        request:
            cache: true
            method: GET
            path: /swagger-ui/swagger.json
        expression: response.status == 200 && response.headers["Content-Type"].contains("application/json") && checker.bmatches(response.body)
    r18:
        request:
            cache: true
            method: GET
            path: /swagger.json
        expression: response.status == 200 && response.headers["Content-Type"].contains("application/json") && checker.bmatches(response.body)
    r19:
        request:
            cache: true
            method: GET
            path: /v1/swagger.json
        expression: response.status == 200 && response.headers["Content-Type"].contains("application/json") && checker.bmatches(response.body)
    r20:
        request:
            cache: true
            method: GET
            path: /v2/swagger.json
        expression: response.status == 200 && response.headers["Content-Type"].contains("application/json") && checker.bmatches(response.body)
    r21:
        request:
            cache: true
            method: GET
            path: /swagger/v1/swagger.json
        expression: response.status == 200 && response.headers["Content-Type"].contains("application/json") && checker.bmatches(response.body)
    r22:
        request:
            cache: true
            method: GET
            path: /swagger/v2/swagger.json
        expression: response.status == 200 && response.headers["Content-Type"].contains("application/json") && checker.bmatches(response.body)
    r23:
        request:
            cache: true
            method: GET
            path: /spec.json
        expression: response.status == 200 && response.headers["Content-Type"].contains("application/json") && checker.bmatches(response.body)
    r24:
        request:
            cache: true
            method: GET
            path: /v2/api-docs
        expression: response.status == 200 && response.headers["Content-Type"].contains("application/json") && checker.bmatches(response.body)
    r25:
        request:
            cache: true
            method: GET
            path: /v1/api-docs
        expression: response.status == 200 && response.headers["Content-Type"].contains("application/json") && checker.bmatches(response.body)
    r26:
        request:
            cache: true
            method: GET
            path: /v2/api-docs.json
        expression: response.status == 200 && response.headers["Content-Type"].contains("application/json") && checker.bmatches(response.body)
expression: r0() || r1() || r2() || r3() || r4() || r5() || r6() || r7() || r8() || r9() || r10() || r11() || r12() || r13() || r14() || r15() || r16() || r17() || r18() || r19() || r20() || r21() || r22() || r23() || r24() || r25() || r26()
