name: yaml-poc-laravel-laravel-unsafe_config-CT-158642
binding: d5898286-156e-4eaa-898e-5fb1fba8c8b5
detail:
    author: system_user
    vulnerability:
        id: a7e5e3d1-4ff5-4f32-b885-cd3a7813fbcf
        level: medium
transport: http
rules:
    r0:
        request:
            cache: true
            method: POST
            path: /
            follow_redirects: false
        expression: response.status == 405 && response.body.bcontains(b"MethodNotAllowedHttpException") && response.body.bcontains(b"Environment &amp; details") && (response.body.bcontains(b"vendor\\laravel\\framework\\src\\Illuminate\\Routing\\RouteCollection.php") || response.body.bcontains(b"vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php"))
expression: r0()
