name: yaml-poc-redhat-jboss_enterprise_application_platform-logical-CVE-2015-7501
binding: 908cb9a0-1da7-4faa-b3b6-285398051564
detail:
    author: system_user
    links:
        - http://rhn.redhat.com/errata/RHSA-2015-2500.html
        - http://rhn.redhat.com/errata/RHSA-2015-2501.html
        - http://rhn.redhat.com/errata/RHSA-2015-2502.html
        - http://rhn.redhat.com/errata/RHSA-2015-2514.html
        - http://rhn.redhat.com/errata/RHSA-2015-2516.html
        - http://rhn.redhat.com/errata/RHSA-2015-2517.html
        - http://rhn.redhat.com/errata/RHSA-2015-2521.html
        - http://rhn.redhat.com/errata/RHSA-2015-2522.html
        - http://rhn.redhat.com/errata/RHSA-2015-2524.html
        - http://rhn.redhat.com/errata/RHSA-2015-2670.html
        - http://rhn.redhat.com/errata/RHSA-2015-2671.html
        - http://rhn.redhat.com/errata/RHSA-2016-0040.html
        - http://rhn.redhat.com/errata/RHSA-2016-1773.html
        - http://www.oracle.com/technetwork/security-advisory/cpuapr2018-3678067.html
        - http://www.oracle.com/technetwork/security-advisory/cpujan2018-3236628.html
        - http://www.oracle.com/technetwork/security-advisory/cpujul2018-4258247.html
        - http://www.oracle.com/technetwork/security-advisory/cpuoct2018-4428296.html
        - http://www.securityfocus.com/bid/78215
        - http://www.securitytracker.com/id/1034097
        - http://www.securitytracker.com/id/1037052
        - http://www.securitytracker.com/id/1037053
        - http://www.securitytracker.com/id/1037640
        - https://access.redhat.com/security/vulnerabilities/2059393
        - https://access.redhat.com/solutions/2045023
        - https://bugzilla.redhat.com/show_bug.cgi?id=1279330
        - https://packetstormsecurity.com/files/159604/Red-Hat-Security-Advisory-2020-4274-01.html
        - https://rhn.redhat.com/errata/RHSA-2015-2536.html
        - https://rhn.redhat.com/errata/RHSA-2015-2537.html
        - https://www.auscert.org.au/bulletins/ESB-2019.3165/
        - https://www.auscert.org.au/bulletins/ESB-2020.3590/
        - https://www.auscert.org.au/bulletins/ESB-2020.4516/
        - https://www.auscert.org.au/bulletins/ESB-2021.0692
        - https://www.ibm.com/blogs/psirt/security-bulletin-multiple-vulnerabilities-in-ibm-websphere-extreme-scale-liberty-deployment/
        - https://www.ibm.com/blogs/psirt/security-bulletin-multiple-vulnerability-issues-affect-ibm-spectrum-symphony-7-3-1/
        - https://www.ibm.com/support/docview.wss?uid=ibm10967469
        - https://www.oracle.com/security-alerts/cpujul2020.html
        - https://www.securityfocus.com/bid/78215
    vulnerability:
        id: cee73ef6-7ac2-49ac-9e2a-f3721d826ac8
        level: critical
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /invoker/JMXInvokerServlet
        expression: response.status == 200 && response.body.bcontains(b"MarshalledValue") && response.content_type.contains("x-java-serialized-object")
expression: r0()
