name: yaml-poc-redhat-jboss_enterprise_application_platform-logical-CVE-2017-7504
binding: 26d3fdb8-3844-488d-a399-5df545698e6a
detail:
    author: system_user
    links:
        - http://www.securityfocus.com/bid/98595
        - https://bugzilla.redhat.com/show_bug.cgi?id=1451441
        - https://nvd.nist.gov/vuln/detail/CVE-2017-7504
        - https://www.securityfocus.com/bid/98595
    vulnerability:
        id: b07ba51c-b0a8-4060-a136-d2b793c6748f
        level: critical
transport: http
rules:
    r0:
        request:
            cache: true
            method: POST
            path: /jbossmq-httpil/HTTPServerILServlet
            headers:
                Content-Type: application/x-www-form-urlencoded
            body: any
        expression: response.status == 200 && response.body.bcontains(b"org.jboss.mq.il.http.servlet")
expression: r0()
