name: poc-yaml-tcp-weblogic-t3-check
binding: 94376781-e1b1-4e70-acff-b84b135257a6
detail:
    author: ykc
transport: tcp
rules:
    r1:
        request:
            cache: true
            content: |+
                t3 12.1.3
                AS:255
                HL:19
                MS:10000000

            read_timeout: "3"
            connection_id: first
        expression: |
            response.raw.bstartsWith(b"HELO")
    r2:
        request:
            cache: true
            content: |+
                t3s 12.1.3
                AS:255
                HL:19
                MS:10000000

            read_timeout: "3"
            connection_id: second
        expression: |
            response.raw.bstartsWith(b"HELO")
expression: r1() || r2()
