name: yaml-poc-prometheus-prometheus-unauthorized_access-CT-630444
binding: 32c2bf54-1ddf-4f75-be52-49440b65bf04
detail:
    author: haiqing.chen
    vulnerability:
        id: d5dbe05b-7055-4e4d-a232-16e34bb63077
        level: high
    warning: Harmless
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /graph
        expression: response.status == 200 && response.body_string.contains("Prometheus") && response.body_string.contains("GLOBAL_READY")
expression: r0()
