name: poc-yaml-tcp-weblogic-iiop-check
binding: 7977dabb-b2a8-419b-a6c4-daf1aa84a1c3
detail:
    author: ykc
transport: tcp
rules:
    r1:
        request:
            cache: true
            content: "GIOP\x01\x02\0\x03\0\0\0\x17\0\0\0\x02\0\0\0\0\0\0\0\vNameService\n"
            read_timeout: 3
        expression: response.raw.bstartsWith(b"GIOP") && response.raw.bcontains(b"weblogic")
expression: r1()
