name: yaml-poc-redhat-jboss_enterprise_application_platform-unauthorized_access-CVE-2017-12149
binding: aafd2945-1c4f-4d22-b6ce-9d651e001a9b
detail:
    author: system_user
    links:
        - http://www.securityfocus.com/bid/100591
        - https://access.redhat.com/errata/RHSA-2018:1607
        - https://access.redhat.com/errata/RHSA-2018:1608
        - https://bugzilla.redhat.com/show_bug.cgi?id=1486220
        - https://github.com/gottburgm/Exploits/tree/master/CVE-2017-12149
    vulnerability:
        id: acbf43cf-c13b-4e07-9f2f-ccccd0521671
        level: critical
    warning: Harmless
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /invoker/readonly
        expression: response.status == 500 && response.body.bcontains(b"EOFExeption") && response.body.bcontains(b"ReadOnlyAccessFilter.java")
expression: r0()
